version: '2'
services:
  postgres:
    image: postgres:9.5.6-alpine
    # The following turns the DB initialization in the postgres image a bit more robust.
    command: "postgres -c wal_level=logical"
  redis:
    image: redis:3.0-alpine
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  worker:
    image: redash/redash:latest
    command: worker
    depends_on:
      - server
