version: "3.8"
name: redash
services:
  server:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: /env
    restart: always
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: /env
    restart: always
    command: scheduler
  worker:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - postgres
      - redis
    env_file: /env
    restart: always
    command: worker
    environment:
      QUEUES: "queries,scheduled_queries,schemas"
      WORKERS_COUNT: 2
  redis:
    image: redis:7.0-alpine
    restart: always
  postgres:
    image: postgres:15-alpine
    env_file: /env
    volumes:
      - /data/postgres-redash-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always